import { useCallback, useEffect, useState, type ReactNode } from "react";
import { Badge } from "./components/ui/badge";
import { Button } from "./components/ui/button";
import { ConfirmDialog } from "./components/ui/confirm-dialog";
// Auto-generated by `wails dev` / `wails build` once app.go methods are bound.
import {
  CreatePlan,
  DeletePlan,
  GetPlans,
  GetPlanSettings,
  RenamePlan,
  RestorePlan,
  SetActive,
  UpdatePlanSettings,
} from "../wailsjs/go/main/App";
import { EventsOn } from "../wailsjs/runtime/runtime";

interface PowerPlan {
  guid: string;
  name: string;
  active: boolean;
  hidden: boolean;
}

interface PlanSettings {
  displayAC: number;
  displayDC: number;
  diskAC: number;
  diskDC: number;
  sleepAC: number;
  sleepDC: number;
}

type TimeUnit = "milliseconds" | "seconds" | "minutes";

const unitSeconds: Record<TimeUnit, number> = {
  milliseconds: 0.001,
  seconds: 1,
  minutes: 60,
};

const emptySettings: PlanSettings = {
  displayAC: 600,
  displayDC: 300,
  diskAC: 1200,
  diskDC: 600,
  sleepAC: 1800,
  sleepDC: 900,
};

export default function App() {
  const [plans, setPlans] = useState<PowerPlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busyGuid, setBusyGuid] = useState<string | null>(null);
  const [pendingDelete, setPendingDelete] = useState<PowerPlan | null>(null);
  const [renaming, setRenaming] = useState<{
    guid: string;
    value: string;
  } | null>(null);
  const [creating, setCreating] = useState(false);
  const [newName, setNewName] = useState("");
  const [sourceGuid, setSourceGuid] = useState("");
  const [configuring, setConfiguring] = useState<PowerPlan | null>(null);
  const [settings, setSettings] = useState<PlanSettings>(emptySettings);
  const [settingsLoading, setSettingsLoading] = useState(false);
  const [timeUnit, setTimeUnit] = useState<TimeUnit>("minutes");

  const refresh = useCallback(async () => {
    setError(null);
    try {
      const result = await GetPlans();
      setPlans(result ?? []);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  // Switching the active plan from the tray icon happens outside this
  // window, so listen for the backend's broadcast and pick up the change.
  useEffect(() => {
    return EventsOn("plans:changed", () => {
      refresh();
    });
  }, [refresh]);

  const withBusy = async (guid: string, fn: () => Promise<void>) => {
    setBusyGuid(guid);
    setError(null);
    try {
      await fn();
      await refresh();
    } catch (e) {
      setError(String(e));
    } finally {
      setBusyGuid(null);
    }
  };

  const active = plans.find((p) => p.active);

  const openSettings = async (plan: PowerPlan) => {
    setConfiguring(plan);
    setSettingsLoading(true);
    setError(null);
    try {
      setSettings(await GetPlanSettings(plan.guid));
    } catch (e) {
      setError(String(e));
      setConfiguring(null);
    } finally {
      setSettingsLoading(false);
    }
  };

  const saveSettings = async () => {
    if (!configuring) return;
    await withBusy(configuring.guid, () =>
      UpdatePlanSettings(configuring.guid, settings),
    );
    setConfiguring(null);
  };

  return (
    <div className="flex h-screen flex-col bg-panel-bg font-sans">
      {/* Header / readout */}
      <header className="border-b border-panel-border px-6 py-5">
        <div className="flex items-center justify-between">
          <div>
            <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-ink-faint">
              Power Plan Switcher
            </p>
            <h1 className="mt-1 font-mono text-2xl font-medium text-ink">
              {loading
                ? "Reading…"
                : active
                  ? active.name
                  : "No active plan detected"}
            </h1>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={refresh}
              disabled={loading}
            >
              Refresh
            </Button>
            <Button
              size="sm"
              variant="primary"
              onClick={() => {
                setNewName("");
                setSourceGuid(active?.guid ?? "");
                setCreating(true);
              }}
            >
              New plan
            </Button>
          </div>
        </div>
      </header>

      {error && (
        <div className="mx-6 mt-4 rounded-sm border border-danger/40 bg-danger/10 px-3 py-2 font-mono text-xs text-danger">
          {error}
        </div>
      )}

      {/* Plan list */}
      <main className="flex-1 overflow-y-auto px-6 py-4">
        <div className="flex flex-col gap-2">
          {plans.map((plan) => {
            const isBusy = busyGuid === plan.guid;
            return (
              <div
                key={plan.guid}
                className="flex items-center gap-4 rounded-md border border-panel-border bg-panel-surface px-4 py-3 transition-colors hover:bg-panel-hover"
              >
                {/* LED indicator */}
                <span
                  className={
                    "h-2.5 w-2.5 shrink-0 rounded-full " +
                    (plan.active
                      ? "bg-amber shadow-glow"
                      : plan.hidden
                        ? "bg-panel-border"
                        : "bg-ink-faint")
                  }
                />

                <div className="min-w-0 flex-1">
                  {renaming?.guid === plan.guid ? (
                    <input
                      autoFocus
                      value={renaming.value}
                      onChange={(e) =>
                        setRenaming({ guid: plan.guid, value: e.target.value })
                      }
                      onKeyDown={(e) => {
                        if (e.key === "Enter") {
                          withBusy(plan.guid, () =>
                            RenamePlan(plan.guid, renaming.value),
                          );
                          setRenaming(null);
                        }
                        if (e.key === "Escape") setRenaming(null);
                      }}
                      onBlur={() => setRenaming(null)}
                      className="w-full rounded-sm border border-amber/40 bg-panel-bg px-2 py-0.5 font-mono text-sm text-ink outline-none"
                    />
                  ) : (
                    <p className="truncate text-sm text-ink">{plan.name}</p>
                  )}
                  <p className="truncate font-mono text-[10px] text-ink-faint">
                    {plan.guid}
                  </p>
                </div>

                {plan.active && <Badge tone="amber">Active</Badge>}
                {plan.hidden && <Badge tone="muted">Not installed</Badge>}

                <div className="flex shrink-0 items-center gap-1.5">
                  {plan.hidden ? (
                    <Button
                      size="sm"
                      variant="primary"
                      disabled={isBusy}
                      onClick={() =>
                        withBusy(plan.guid, () => RestorePlan(plan.guid))
                      }
                    >
                      Restore
                    </Button>
                  ) : (
                    <>
                      <Button
                        size="sm"
                        variant="ghost"
                        disabled={isBusy}
                        onClick={() =>
                          setRenaming({ guid: plan.guid, value: plan.name })
                        }
                      >
                        Rename
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        disabled={isBusy}
                        onClick={() => openSettings(plan)}
                      >
                        Configure
                      </Button>
                      <Button
                        size="sm"
                        variant="primary"
                        disabled={isBusy || plan.active}
                        onClick={() =>
                          withBusy(plan.guid, () => SetActive(plan.guid))
                        }
                      >
                        Activate
                      </Button>
                      <Button
                        size="sm"
                        variant="danger"
                        disabled={isBusy || plan.active}
                        onClick={() => setPendingDelete(plan)}
                      >
                        Delete
                      </Button>
                    </>
                  )}
                </div>
              </div>
            );
          })}

          {!loading && plans.length === 0 && !error && (
            <p className="py-10 text-center text-sm text-ink-faint">
              No power plans found.
            </p>
          )}
        </div>
      </main>

      <ConfirmDialog
        open={pendingDelete !== null}
        title="Delete power plan"
        description={`This permanently removes "${pendingDelete?.name}". This can't be undone.`}
        confirmLabel="Delete"
        onCancel={() => setPendingDelete(null)}
        onConfirm={() => {
          if (pendingDelete)
            withBusy(pendingDelete.guid, () => DeletePlan(pendingDelete.guid));
          setPendingDelete(null);
        }}
      />

      {creating && (
        <PlanDialog
          title="Create power plan"
          onClose={() => setCreating(false)}
        >
          <p className="text-xs text-ink-muted">
            Creates a copy so your current settings remain a useful starting
            point.
          </p>
          <label className="flex flex-col gap-1.5 font-mono text-[10px] uppercase tracking-wide text-ink-faint">
            Plan name
            <input
              autoFocus
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              className="rounded-sm border border-panel-border bg-panel-bg px-2 py-2 text-sm normal-case tracking-normal text-ink outline-none focus:border-amber/60"
            />
          </label>
          <label className="flex flex-col gap-1.5 font-mono text-[10px] uppercase tracking-wide text-ink-faint">
            Copy settings from
            <select
              value={sourceGuid}
              onChange={(e) => setSourceGuid(e.target.value)}
              className="rounded-sm border border-panel-border bg-panel-bg px-2 py-2 text-sm normal-case tracking-normal text-ink outline-none focus:border-amber/60"
            >
              {plans
                .filter((p) => !p.hidden)
                .map((p) => (
                  <option key={p.guid} value={p.guid}>
                    {p.name}
                    {p.active ? " (active)" : ""}
                  </option>
                ))}
            </select>
          </label>
          <DialogActions
            onCancel={() => setCreating(false)}
            onConfirm={async () => {
              if (!newName.trim()) return;
              await withBusy("new-plan", () => CreatePlan(newName, sourceGuid));
              setCreating(false);
            }}
            confirmLabel="Create"
            disabled={!newName.trim() || busyGuid === "new-plan"}
          />
        </PlanDialog>
      )}

      {configuring && (
        <PlanDialog
          title={`Configure ${configuring.name}`}
          onClose={() => setConfiguring(null)}
        >
          {settingsLoading ? (
            <p className="text-sm text-ink-muted">Reading current settings…</p>
          ) : (
            <>
              <div className="flex items-end justify-between gap-4">
                <p className="text-xs text-ink-muted">
                  Use 0 for Never. Windows stores whole seconds; milliseconds
                  are rounded when saved.
                </p>
                <label className="flex shrink-0 flex-col gap-1 font-mono text-[10px] uppercase tracking-wide text-ink-faint">
                  Unit
                  <select
                    value={timeUnit}
                    onChange={(e) => setTimeUnit(e.target.value as TimeUnit)}
                    className="rounded-sm border border-panel-border bg-panel-bg px-2 py-1.5 text-xs normal-case tracking-normal text-ink outline-none focus:border-amber/60"
                  >
                    <option value="milliseconds">Milliseconds</option>
                    <option value="seconds">Seconds</option>
                    <option value="minutes">Minutes</option>
                  </select>
                </label>
              </div>
              <div className="grid grid-cols-[1fr_80px_80px] gap-2 text-xs">
                <span className="font-mono text-[10px] uppercase text-ink-faint">
                  Timeout
                </span>
                <span className="font-mono text-[10px] uppercase text-ink-faint">
                  Plugged in
                </span>
                <span className="font-mono text-[10px] uppercase text-ink-faint">
                  Battery
                </span>
                <TimeoutRow
                  label="Turn off display"
                  setting="display"
                  settings={settings}
                  unit={timeUnit}
                  onChange={setSettings}
                />
                <TimeoutRow
                  label="Turn off disk"
                  setting="disk"
                  settings={settings}
                  unit={timeUnit}
                  onChange={setSettings}
                />
                <TimeoutRow
                  label="Put device to sleep"
                  setting="sleep"
                  settings={settings}
                  unit={timeUnit}
                  onChange={setSettings}
                />
              </div>
              <DialogActions
                onCancel={() => setConfiguring(null)}
                onConfirm={saveSettings}
                confirmLabel="Save settings"
                disabled={busyGuid === configuring.guid}
              />
            </>
          )}
        </PlanDialog>
      )}
    </div>
  );
}

function PlanDialog({
  title,
  children,
  onClose: _onClose,
}: {
  title: string;
  children: ReactNode;
  onClose: () => void;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4 backdrop-blur-sm">
      <div className="flex w-full max-w-md flex-col gap-4 rounded-md border border-panel-border bg-panel-surface p-5 shadow-2xl">
        <h2 className="font-mono text-sm font-medium text-ink">{title}</h2>
        {children}
      </div>
    </div>
  );
}

function DialogActions({
  onCancel,
  onConfirm,
  confirmLabel,
  disabled,
}: {
  onCancel: () => void;
  onConfirm: () => void;
  confirmLabel: string;
  disabled?: boolean;
}) {
  return (
    <div className="flex justify-end gap-2">
      <Button variant="ghost" size="sm" onClick={onCancel}>
        Cancel
      </Button>
      <Button
        variant="primary"
        size="sm"
        onClick={onConfirm}
        disabled={disabled}
      >
        {confirmLabel}
      </Button>
    </div>
  );
}

function TimeoutRow({
  label,
  setting,
  settings,
  unit,
  onChange,
}: {
  label: string;
  setting: "display" | "disk" | "sleep";
  settings: PlanSettings;
  unit: TimeUnit;
  onChange: (settings: PlanSettings) => void;
}) {
  const factor = unitSeconds[unit];
  const value = (key: "AC" | "DC") =>
    settings[`${setting}${key}` as keyof PlanSettings] / factor;
  const update = (key: "AC" | "DC", input: string) =>
    onChange({
      ...settings,
      [`${setting}${key}`]: Math.max(
        0,
        Math.round((Number(input) || 0) * factor),
      ),
    } as PlanSettings);
  return (
    <>
      <label className="self-center text-ink-muted">{label}</label>
      <input
        type="number"
        min="0"
        max={604800 / factor}
        step={unit === "milliseconds" ? 1 : "any"}
        value={value("AC")}
        onChange={(e) => update("AC", e.target.value)}
        className="w-full rounded-sm border border-panel-border bg-panel-bg px-2 py-1 text-ink outline-none focus:border-amber/60"
      />
      <input
        type="number"
        min="0"
        max={604800 / factor}
        step={unit === "milliseconds" ? 1 : "any"}
        value={value("DC")}
        onChange={(e) => update("DC", e.target.value)}
        className="w-full rounded-sm border border-panel-border bg-panel-bg px-2 py-1 text-ink outline-none focus:border-amber/60"
      />
    </>
  );
}
