// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePlan(arg1, arg2) {
  return window['go']['main']['App']['CreatePlan'](arg1, arg2);
}

export function DeletePlan(arg1) {
  return window['go']['main']['App']['DeletePlan'](arg1);
}

export function GetPlanSettings(arg1) {
  return window['go']['main']['App']['GetPlanSettings'](arg1);
}

export function GetPlans() {
  return window['go']['main']['App']['GetPlans']();
}

export function RenamePlan(arg1, arg2) {
  return window['go']['main']['App']['RenamePlan'](arg1, arg2);
}

export function RestorePlan(arg1) {
  return window['go']['main']['App']['RestorePlan'](arg1);
}

export function SetActive(arg1) {
  return window['go']['main']['App']['SetActive'](arg1);
}

export function UpdatePlanSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdatePlanSettings'](arg1, arg2);
}
