// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreatePlan(arg1:string,arg2:string):Promise<void>;

export function DeletePlan(arg1:string):Promise<void>;

export function GetPlanSettings(arg1:string):Promise<main.PlanSettings>;

export function GetPlans():Promise<Array<main.PowerPlan>>;

export function RenamePlan(arg1:string,arg2:string):Promise<void>;

export function RestorePlan(arg1:string):Promise<void>;

export function SetActive(arg1:string):Promise<void>;

export function UpdatePlanSettings(arg1:string,arg2:main.PlanSettings):Promise<void>;
